function OutsideImage(_props) {
  return (
    <div class="col-start-2 col-span-1 invisible md:visible mx-auto my-auto">
      <img
        id="cells"
        src="/images/cells.png"
        alt="Cells"
        title="Cells generated by AI"
        class="w-64 h-64"
      />
    </div>
  );
}

export default OutsideImage;
