const {
  VITE_ENVIRONMENT,
  VITE_BACKEND_URL,
  VITE_FRONTEND_URL,
  VITE_SUPPORT_EMAIL,
  VITE_LOCAL_STORAGE_JWT,
  VITE_LOCAL_STORAGE_USER_TYPE,
  VITE_USER_STATUS_PENDING_EMAIL_CONFIRMATION,
  VITE_USER_STATUS_EMAIL_CONFIRMED,
  VITE_MAX_CONVENTIONAL_PROJECTS,
  VITE_MAX_PHOTO_PROJECTS,
  VITE_PROJECT_TYPE_CONVENTIONAL,
  VITE_PROJECT_TYPE_PHOTO,
  VITE_PROJECT_WAITING_EXAMINER,
  VITE_PROJECT_PENDING_REVIEW,
  VITE_PROJECT_PARTIALLY_APPROVED,
  VITE_PROJECT_APPROVED,
  VITE_PROJECT_REJECTED,
} = import.meta.env;

const env = {
  ENVIRONMENT: VITE_ENVIRONMENT,
  BACKEND_URL: VITE_BACKEND_URL,
  FRONTEND_URL: VITE_FRONTEND_URL,
  SUPPORT_EMAIL: VITE_SUPPORT_EMAIL,
  LOCAL_STORAGE_JWT: VITE_LOCAL_STORAGE_JWT,
  LOCAL_STORAGE_USER_TYPE: VITE_LOCAL_STORAGE_USER_TYPE,
  USER_STATUS_PENDING_EMAIL_CONFIRMATION: VITE_USER_STATUS_PENDING_EMAIL_CONFIRMATION,
  USER_STATUS_EMAIL_CONFIRMED: VITE_USER_STATUS_EMAIL_CONFIRMED,
  MAX_CONVENTIONAL_PROJECTS: VITE_MAX_CONVENTIONAL_PROJECTS,
  MAX_PHOTO_PROJECTS: VITE_MAX_PHOTO_PROJECTS,
  PROJECT_TYPE_CONVENTIONAL: VITE_PROJECT_TYPE_CONVENTIONAL,
  PROJECT_TYPE_PHOTO: VITE_PROJECT_TYPE_PHOTO,
  PROJECT_WAITING_EXAMINER: VITE_PROJECT_WAITING_EXAMINER,
  PROJECT_PENDING_REVIEW: VITE_PROJECT_PENDING_REVIEW,
  PROJECT_PARTIALLY_APPROVED: VITE_PROJECT_PARTIALLY_APPROVED,
  PROJECT_APPROVED: VITE_PROJECT_APPROVED,
  PROJECT_REJECTED: VITE_PROJECT_REJECTED
};

export default env;
